### ISSUE TITLE
Key count does not go up if pressing same key multiple times in a row.

### ISSUE THREAD

**Issue by ghost** [soapskyway/keycount#3]
As reported, the count doesn't go up if you press the same key multiple times in a row. It only goes up if different keys are pressed.

If it makes a difference, I'm running this on Atom 1.12.7 and the keycount version is 0.1.1. My operating system is Linux Mint 18.

**Comment by soapskyway** [comment]
I am not able to test this on Linux, but on my computer it works fine. There has been a lot of changes in the key event area in Atom that might cause this.
